export const EMPLOYEE_LOAD_SUCCESS = 'EMPLOYEE_LOAD_SUCCESS';
export const SEARCHED_EMPLOYEE = 'SEARCHED_EMPLOYEE';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR';
export const ALL_EMPLOYEES = 'ALL_EMPLOYEES';
export const POST_DATA = 'POST_DATA';
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';